# Generated by Django 6.0.5 on 2026-05-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
